### ISSUE TITLE
how to add drag and drop effect in chess by only typescript can u clear my doubt bro !

### ISSUE THREAD

**Issue by ayansiddiqui007** [dwenner/typescript-chess#1]
#codedoubt

**Comment by dwenner** [comment]
Not really, This was just an experiment I did 5 years ago to learn some Typescript, and I'm not planning on doing additional work on it.

If you want to do it in Typescript with no dependencies the best way to do it is probably just to implement the events for the [HTML Drag and Drop API](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API).
